//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaTransporte
    {
        public int RutaTransporteId { get; set; }
        public Nullable<int> RutaId { get; set; }
        public Nullable<int> TransporteId { get; set; }
    
        public virtual Ruta Ruta { get; set; }
        public virtual Transporte Transporte { get; set; }
    }
}
